# Generated by Django 4.1.1 on 2022-09-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('DO', 'Выполнено'), ('DR', 'В процессе'), ('NS', 'Не начата')], default='NS', max_length=100, verbose_name='Статус'),
        ),
    ]
