# Generated by Django 4.1.1 on 2022-09-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_tasks_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='set_st',
            field=models.CharField(choices=[('DO', 'Выполнено'), ('DR', 'В процессе'), ('NS', 'Не начата')], default='NS', max_length=5, verbose_name='Статус'),
        ),
    ]
