# Generated by Django 4.1.1 on 2022-09-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_tasks_set_st'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='status',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='set_st',
            field=models.CharField(choices=[('DO', 'Выполнено'), ('DR', 'В процессе'), ('NS', 'Не начата')], max_length=5, verbose_name='Статус'),
        ),
    ]
