# Generated by Django 4.1.1 on 2022-09-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_remove_tasks_status_alter_tasks_set_st'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='data_do',
            field=models.DateField(auto_now_add=True, verbose_name='Дата выполненияя'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='set_st',
            field=models.CharField(choices=[('Done', 'Выполнено'), ('During', 'В процессе'), ('New', 'Не начата')], max_length=9, verbose_name='Статус'),
        ),
    ]
