# Generated by Django 4.1.1 on 2022-09-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_tasks_data_do'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='data_do',
            field=models.DateField(auto_now_add=True, verbose_name='Дата выполненияя'),
        ),
    ]
